# Generated by Django 4.1 on 2022-10-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_appe', '0002_alter_banner_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='productattributes',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
    ]
